2024-01-19 17:08:47,378 ERROR: Exception on /products/read/6 [GET] [in C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_debugtoolbar\__init__.py", line 157, in dispatch_request
    return view_func(**req.view_args)
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "C:\Users\oscar\OneDrive\Escritorio\DAW2\m12-projecte\wannapop\routes_main.py", line 89, in product_read
    current_app.logger.debug(product.to_json())
NameError: name 'item' is not defined
2024-01-19 17:08:47,378 ERROR: Exception on /products/read/6 [GET] [in C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_debugtoolbar\__init__.py", line 157, in dispatch_request
    return view_func(**req.view_args)
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "C:\Users\oscar\OneDrive\Escritorio\DAW2\m12-projecte\wannapop\routes_main.py", line 89, in product_read
    current_app.logger.debug(product.to_json())
NameError: name 'item' is not defined
2024-01-19 17:08:51,478 INFO: Accés a la pàgina principal [in C:\Users\oscar\OneDrive\Escritorio\DAW2\m12-projecte\wannapop\routes_main.py:20]
2024-01-19 17:08:51,478 INFO: Accés a la pàgina principal [in C:\Users\oscar\OneDrive\Escritorio\DAW2\m12-projecte\wannapop\routes_main.py:20]
